# 개발 서버 테스트
@oauth_hostname = 127.0.0.1
@oauth_port = 3001
@oauth_host = {{oauth_hostname}}:{{oauth_port}}
@api_hostname = 127.0.0.1
@api_port = 3000
@api_host = {{api_hostname}}:{{api_port}}
@contentType = application/json

###
# @name requestAccessTokenWithClientCredentials
# 1. client-credentials 로 AccessToken 발급 요청
@grant_type=client_credentials
@client_id=dummy-client-id
@client_secret=dummy-client-secret
POST http://{{oauth_host}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type={{grant_type}}&client_id={{client_id}}&client_secret={{client_secret}}

###
# @name requestApiWithAccessToken
# 2. 다랑안내 이력 조회 - 필수 조건만
@1_start_date=20190614000000
@1_end_date=20190630235959
@1_user_id=devTest001
@1_ani=02-9999-1234
@1_ann_name=테스트
GET http://{{api_host}}/getMultiAnnounce?START_DATE={{1_start_date}}&END_DATE={{1_end_date}}&USER_ID={{1_user_id}}&ANI={{1_ani}}&ANN_NAME={{1_ann_name}} HTTP/1.1
Authorization: {{requestAccessTokenWithClientCredentials.response.body.$.token_type}} {{requestAccessTokenWithClientCredentials.response.body.$.access_token}}

# validation access token
# https://graph.facebook.com/me?access_token={accessToken}
# https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={accessToken}
# https://<region>.onelogin.com/oidc/token/introspection
# https://api.github.com/user?access_token=<access_token_val>
